### ISSUE TITLE
HU-21 Diseñar mockup landing

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#10]
> [!WARNING]
> Deribada de la HU-16.

**Comment by nuhacet66** [comment]
Vamos a tener que darle una vuelta otra vez a los colores ya que nos sale con un nivel muy bajo de contraste con los colores actuales

**Comment by nuhacet66** [comment]
Hay que cambiar los colores ya que tenemos muy bajo contraste para la parte de accesibilidad

**Comment by JuanCarlosAcostaPeraba** [comment]
Finalizada la hero de la landing.

![Image](https://github.com/PS-G1-Lab/control-horas/assets/43654546/326a1311-2238-4703-a28f-1469c21757ca)

**Comment by JuanCarlosAcostaPeraba** [comment]
Refactor the learn section and footer.
Create the reviews section.

![learn-section](https://github.com/PS-G1-Lab/control-horas/assets/43654546/639078ce-50f5-43d8-8d55-7886cca0ef1e)


![footer](https://github.com/PS-G1-Lab/control-horas/assets/43654546/fb32aeb9-b35a-4267-b5b4-37b407072091)

![reviews-section](https://github.com/PS-G1-Lab/control-horas/assets/43654546/298bc5cf-4b33-47af-8f2c-67d828a30748)

**Comment by nuhacet66** [comment]
Finish the information about the Website.



![Image](https://github.com/PS-G1-Lab/control-horas/assets/22832413/fde3ae44-2591-4172-b2f1-5190a48754a3)

**Comment by JuanCarlosAcostaPeraba** [comment]
Finish the 'Landing Page' mockup.

![Image](https://github.com/PS-G1-Lab/control-horas/assets/43654546/7bbd2d90-c4f1-4e98-98e4-b53b1704a3e8)
