### ISSUE TITLE
Poner diferentes idiomas

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#100]
# Descripción

**Como** usuario,
**Quiero** tener la capacidad de traducir la página web 
**Para** poder leerla en mi idioma nativo o en uno que pueda entender.

# Criterios de validación

- [x] Verificar que dicha traducción se mantenga en el cambio de ventanas.
- [x] Verificar que el desplegable de traducción aparezcan en el Header y en el Header alternativo.
- [x] Los idiomas que estarán en la página web serán todas las proporcionadas por Google.
- [x] El desplegable de traducción en el Header tiene que estar ubicado a la derecha de los botones del menú.
- [x] El desplegable de traducción en el Header alternativo aparecerá a la izquierda del icono del usuario.

**Comment by nuhacet66** [comment]
Arreglar el diseño de "Contáctanos si necesitas asistencia" ya que se queda cortado. Posible solución: "Contáctanos si" ,"necesitas asistencia".



![Image](https://github.com/PS-G1-Lab/control-horas/assets/22832413/a2c09dde-7c42-4d7c-9d13-2bee3086f659)
