### ISSUE TITLE
HU-22 Diseñar mockup formulario registro/inicio sesión

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#11]
> [!WARNING]
> Deribada de la HU-16.

**Comment by JuanCarlosAcostaPeraba** [comment]
Finish the 'Sign in' mockup.

![Image](https://github.com/PS-G1-Lab/control-horas/assets/43654546/83e8281d-e5dc-4e24-ad35-bb4a235e9394)

**Comment by SilviaGonz** [comment]
Modification of inputs to adapt them to the registration page.

![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/25c35060-8bc7-46b5-ad5f-06f4006d2488)

**Comment by SilviaGonz** [comment]
input color change ##E6622E -> #4C4C4C of the registration and login pages.

![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/af4e3a6c-80a1-49bd-9c13-91f9788b0c42)
![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/2206434e-8c54-4053-a339-8e82aa7ee0b6)
![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/9a4ae196-5138-4ae5-8911-d761a5cfdff3)

**Comment by SilviaGonz** [comment]
Esta HU no la definimos??
