### ISSUE TITLE
HU-23 Diseñar mockup panel de creación de clases

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#12]
> [!WARNING]
> Deribada de la HU-16.

**Comment by nuhacet66** [comment]
Finish the view about search a new class.



![Image](https://github.com/PS-G1-Lab/control-horas/assets/22832413/f1d674fa-91ae-48d0-9d60-5ad360f2d610)

**Comment by SilviaGonz** [comment]
Modificate the hours to price

![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/fcbff480-7ed3-4426-9459-c457b62543ee)

**Comment by Kilamper** [comment]
Class Creation Panel Finished

![Image](https://github.com/PS-G1-Lab/control-horas/assets/73082382/80f99e70-6ed1-4ef8-a6a2-00a59ed0d312)
