### ISSUE TITLE
HU-10 Cierre de sesión

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#14]
# Descripción

Como usuario registrado, quiero poder cerrar mi sesión en el sistema.

# Criterios de validación

Debe haber un botón en la interfaz que permita al usuario cerrar sesión y volver a la página de inicio de la aplicación.

**Comment by nuhacet66** [comment]
Me gustaría que me dijeran si el tiempo que he puesto para la salida y redirección hacia la pagina index es suficiente, le he puesto "3000"
