### ISSUE TITLE
HU-03 Inicio de sesión de usuario

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#15]
# Descripción

Como usuario quiero poder iniciar sesión en el sistema para acceder a mi cuenta y ver mi panel de administración.

# Criterios de validación

Debe haber un formulario de inicio de sesión con campos para el correo electrónico y la contraseña. Se debe verificar que las credenciales sean válidas antes de permitir el acceso al panel de control del usuario.

**Comment by SilviaGonz** [comment]
Card size adjustment and svg change
![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/595bd676-131c-43e8-aab6-e08692e8a2e3)
