### ISSUE TITLE
HU-20 Landing de la aplicación

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#16]
# Descripción

Como usuario, quiero ver una página principal (landing page) con la que pueda saber de qué trata la web.

# Criterios de validación

La landing debe respetar los estándares WCAG (Web Content Accessibility Guidelines).

**Comment by JuanCarlosAcostaPeraba** [comment]
@Kilamper Empiezo ha crear el componente del `header` siguiendo el diseño del mockup.


![Image](https://github.com/PS-G1-Lab/control-horas/assets/43654546/8b3fa014-0548-4cff-af09-650780fc8f13)

**Comment by Kilamper** [comment]
@JuanCarlosAcostaPeraba Comienzo con la creación del `footer` a raíz de lo planteado en los mockups.

![Image](https://github.com/PS-G1-Lab/control-horas/assets/73082382/ca642eb2-6a0f-420b-99f5-70aca59970b7)
