### ISSUE TITLE
HU-09 Cambio de contraseña

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#17]
# Descripción

Como usuario registrado, quiero poder cambiar mi contraseña en el sistema.

# Criterios de validación

Debe haber una página donde pueda cambiar mi contraseña actual por una nueva desde el panel de actualización personal.

**Comment by SilviaGonz** [comment]
Mokups of the change de password
![image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/18f254c1-62b8-42aa-b882-8e0e34641bd9)

**Comment by SilviaGonz** [comment]
Change of design of password boxes and svg

![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/87690ceb-7c7a-4bd9-b6bc-d0cc32248f99)

**Comment by SilviaGonz** [comment]
Add the box text "correo"
![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/ba925a14-99d5-4c0d-a257-bcbff121b462)
