### ISSUE TITLE
HU-08 Actualización de información de perfil

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#18]
# Descripción

Como usuario registrado, quiero poder actualizar mi información personal.

# Criterios de validación

Debe haber una página donde pueda ver y editar mi información personal, incluyendo nombre, apellido y dirección de correo electrónico.

**Comment by SilviaGonz** [comment]
Mockup of profile page
![Image](https://github.com/PS-G1-Lab/control-horas/assets/151831773/21f3ea1e-84dd-4628-bd6a-84b9e517ac57)
