### ISSUE TITLE
Panel de administración de clases

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#23]
# Descripción

**Como** profesor
**Quiero** poder acceder a un panel donde pueda gestionar todas las clases que tengo programadas
**Para** organizarme la planificación.

# Criterios de validación

- [x]  Los campos que se mostrarán en el panel de gestión es el nombre, días, ámbito, número de alumnos inscritos, hora de inicio y hora de finalización de la clase
- [x] Debe existir un botón llamado `Anular clase` que anule la clase creada
- [x] Debe existir un botón llamado `Editar clase` que  redirija a otra página donde se muestre los campos: título, fecha, hora de inicio, hora de finalización, precio y descripción con la información de la clase para poder modificarla
- [ ] Debe existir un botón llamado `Crear clase` que  redirija a la misma página que la descrita anteriormente para poder crear la clase

**Comment by SilviaGonz** [comment]
El botón "crear clase" debe redirigir al panel de creación de clase que ya se implementó en el sprint anterior
