### ISSUE TITLE
Centrar Footer en móviles

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#93]
<img width="481" alt="image" src="https://github.com/PS-G1-Lab/control-horas/assets/43654546/46b933be-1b01-45f0-ab9e-e9afd3363023">

**Comment by eamarquezh** [comment]
Hola @JuanCarlosAcostaPeraba;

Realice una propuesta, espero se adapte mejor a sus requerimientos, aunque tambien me gusto como se ve con beetwen que lo pega a las paredes pero se quedaria de la siguiente forma en  mi propuesta, si quieres mejorarla dame mas detalles y lo puedo trabajar.

![image](https://github.com/PS-G1-Lab/control-horas/assets/10810956/ceac7c44-6ba5-49b7-ac55-75963fc937b3)

Saludos.
