### ISSUE TITLE
Arreglar log in en vista mobile

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas#95]
# Descripción

**Como** desarrollador
**Quiero** que las etiquetas `label` del formulario no se salgan de la pantalla en los dispositivos móviles
**Para** cumplir con el diseño responsive.

# Criterios de validación

- [x] Los campos del formulario Correo y Contraseña deben aparecer dentro de la pantalla.
- [x] Deben verse los campos dentro de la pantalla para dispositivos móviles IOS y Android.

# Error

![Image](https://github.com/PS-G1-Lab/control-horas/assets/43654546/d59922ae-0b57-4a9a-a019-a5a44ad52054)

**Comment by SilviaGonz** [comment]
Esa imagen es del registro y la HU corresponde al login, te confundiste sin darte cuenta. @JuanCarlosAcostaPeraba
